server:
  port: 8081

spring:
  config:
    import: aws-secretsmanager:resident_meeting

  r2dbc:
    url: r2dbc:mysql://${db_host}:3306/resident?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: ${db_username}
    password: ${db_password}
    pool:
      max-size: 100
      validation-query: SELECT 1

  kafka:
    bootstrap-servers: http://kafka-service:9092

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans

user-service-url: http://user-service:8080


event:
  delay: 5